Adding Pensu as owners
kubernetes-sigs/contributor-tweets pull request #30
Opened 2020-12-09 10:47 UTC by Pensu

CC: @mbbroberg

2020-12-09 10:48 UTC, Pensu commented
@mbbroberg I am member of Kubernetes github org. I assumed that covered kubernetes-sigs as well. Do I need to do that separately?

2020-12-09 10:48 UTC, rajula96reddy approved these changes
/lgtm

2020-12-09 10:50 UTC, rajula96reddy commented
> @mbbroberg I am member of Kubernetes github org. I assumed that covered kubernetes-sigs as well. Do I need to do that separately? CC: @rajula96reddy

I think we are good. Once we merge this, you will have access.

2020-12-09 10:53 UTC, mrbobbytables commented
You will need to be added to the k-sigs org via the k/org repo. As a member of Kubernetes, you're implicitly allowed to join the other orgs, its just not automatic.

2020-12-09 14:18 UTC, palnabarun requested changes

2020-12-09 14:18 UTC, palnabarun commented on OWNERS
> +  - Pensu
nit: can you please sort the list? :)
```suggestion
  - Pensu
  - rajula96reddy
```

2020-12-09 17:43 UTC, mbbroberg commented
@Pensu +1 to what Bob said -- we can get the overall org in the other repo. Post nit this lgtm too.

2020-12-11 08:22 UTC, Pensu commented
@palnabarun Sorted! PTAL.

2020-12-14 05:28 UTC, mbbroberg commented
/lgtm

2020-12-14 05:29 UTC, merged